trigger:
 branches:
  include:
  - feature/*
  - develop
  - release/*
  - hotfix/*
  - main    

variables:
  # Web app name
  webAppName: 'APP_CUENTA_ABANDONADA'
  namepool: 'AgentsOnpremiseICETEX'
  nameArtefacto: 'APP_CUENTA_ABANDONADA'
  ${{ if startsWith(variables['System.TeamFoundationCollectionUri'], 'https://dev.azure.com/') }}:
    OrganizationName: $[ replace(variables['System.TeamFoundationCollectionUri'], 'https://dev.azure.com/', '') ]
    OrganizationNameFinal: $[ replace(variables['OrganizationName'], '/', '') ]
  
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
    branchNameFinal: $[ replace(variables['branchName'], '/', '-') ]

  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
    branchNameFinal: $[ replace(variables['branchName'], '/', '-') ]

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    buildProfile: ""

  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    buildProfile: qa

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    buildProfile: production
stages:
- stage: Build
  displayName: 'Stage Build'
  jobs:
  - job: BuildJob
    displayName: 'Proceso Compilacion'
    pool:
      name: $(namepool)
    workspace:
      clean: all 
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.17.1'
        displayName: 'Instalando Node.js'
      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          npm install 
        displayName: 'Instalando npm'
      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          npm install -g @angular/cli
        displayName: 'Instalando Angular CLI'
      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          npm run build$(buildProfile)
        displayName: 'Compilando'
      - task: ArchiveFiles@2
        displayName: 'Creando Artefacto'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/dist/BaseApp'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
          verbose: true
      - task: PublishBuildArtifacts@1
        displayName: 'Publicando Artefacto'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: $(nameArtefacto)
          publishLocation: 'Container'